# Generated by Django 5.2.2 on 2025-06-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="text",
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="匿名", max_length=100),
            preserve_default=False,
        ),
    ]
